-- Ejercicio 1
DELIMITER $$
CREATE EVENT evento1
ON SCHEDULE EVERY 1 MINUTE
STARTS CURRENT_TIMESTAMP
DO
   BEGIN
      INSERT INTO momentos VALUES (NOW());
      DELETE FROM noticias
      WHERE fecha > DATE_SUB(NOW(), INTERVAL 1 HOUR);
   END;$$
DELIMITER ;

-- Ejercicio 2
DELIMITER $$

CREATE TABLE temp(
   ---
)

CREATE EVENT evento2
ON SCHEDULE EVERY 1 DAY
STARTS CURRENT_TIMESTAP
DO
   BEGIN
      INSERT INTO temp
